/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-08-22 00:15:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class list_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("	#condition{overflow: hidden;}\n");
      out.write("	#condition form{float: left;}\n");
      out.write("	#condition #right{float: right;}\n");
      out.write("	#condition button {padding: 5px 10px;}\n");
      out.write("	#tbl1 table {border: 2px solid gray; padding: 10px}\n");
      out.write("	\n");
      out.write("</style>\n");
      out.write("<h1>주문목록</h1>\n");
      out.write("<div id=\"condition\">\n");
      out.write("	<form name=\"frm\">\n");
      out.write("		<select id=\"key\">\n");
      out.write("			<option value=\"order_id\">주문번호</option>\n");
      out.write("			<option value=\"name\" selected>주문자명</option>\n");
      out.write("			<option value=\"pdate\">주문일</option>\n");
      out.write("			<option value=\"address\">주문자주소</option>\n");
      out.write("			<option value=\"tel\">주문자번호</option>\n");
      out.write("			<option value=\"status\">주문자번호</option>\n");
      out.write("		</select>\n");
      out.write("		<input type=\"text\" id=\"word\" placeholder=\"검색어\">\n");
      out.write("		<select id=\"per\">\n");
      out.write("			<option value=\"2\"selected>2행</option>\n");
      out.write("			<option value=\"7\">7행</option>\n");
      out.write("			<option value=\"10\" >10행</option>\n");
      out.write("			<option value=\"15\">15행</option>\n");
      out.write("		</select>\n");
      out.write("		<button>검색</button>검색수:<span id=\"total\"></span>\n");
      out.write("	</form>\n");
      out.write("	<div id=\"right\">\n");
      out.write("		<select id=\"order\">\n");
      out.write("			<option value=\"order_id\">주문번호</option>\n");
      out.write("			<option value=\"name\">주문자명</option>\n");
      out.write("			<option value=\"pdate\">주문일</option>\n");
      out.write("			<option value=\"address\">주문자주소</option>\n");
      out.write("			<option value=\"tel\">주문자번호</option>\n");
      out.write("		</select>\n");
      out.write("		<select id=\"desc\">\n");
      out.write("			<option value=\"asc\">오름차순</option>\n");
      out.write("			<option value=\"desc\" selected>내림차순</option>\n");
      out.write("		</select>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<table id=\"tbl\"></table>\n");
      out.write("<script id=\"temp\" type=\"text/x-handlebars-template\">\n");
      out.write("   <tr class=\"title\">\n");
      out.write("      <td width=100>주문번호</td>\n");
      out.write("      <td width=200>주문자명</td>\n");
      out.write("      <td width=500>주소</td>\n");
      out.write("      <td width=200>번호</td>\n");
      out.write("	  <td width=200>주문일</td>\n");
      out.write("      <td width=200>구매정보</td>\n");
      out.write("   </tr>\n");
      out.write("   {{#each array}}\n");
      out.write("   <tr class=\"row\">\n");
      out.write("      <td>{{order_id}}</td>\n");
      out.write("      <td>{{name}}</td>\n");
      out.write("      <td>{{address}}</td>\n");
      out.write("      <td>{{tel}}</td>\n");
      out.write("		<td>{{pdate}}</td>\n");
      out.write("      <td><button id=\"{{order_id}}\">정보</button></td>\n");
      out.write("   </tr>\n");
      out.write("   {{/each}}\n");
      out.write("</script>\n");
      out.write("<div class=\"buttons\">\n");
      out.write("   <button id=\"prev\">이전</button>\n");
      out.write("   <span id=\"page\">1/10</span>\n");
      out.write("   <button id=\"next\">다음</button>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!--구매자정보-->\n");
      out.write("\n");
      out.write("<div id=\"tbl1\"></div>\n");
      out.write("<script id=\"temp1\" type=\"text/x-handlebars-template\">\n");
      out.write("<h2>구매자정보</h2>\n");
      out.write(" <table>\n");
      out.write("	<tr>\n");
      out.write("		<td class=\"title\" width=150>구매자이름</td>\n");
      out.write("		<td width=100>{{pur.name}} / {{pur.order_id}}</td>\n");
      out.write("		<td class=\"title\" width=100>전화</td>\n");
      out.write("		<td width=200>{{pur.tel}}</td>\n");
      out.write("		<td class=\"title\" width=100>이메일</td>\n");
      out.write("		<td width=100>{{pur.email}}</td>\n");
      out.write("		<td class=\"title\" width=100>주문일</td>\n");
      out.write("		<td width=300>{{pur.pdate}}</td>\n");
      out.write("	</tr>\n");
      out.write("	<tr>\n");
      out.write("		<td class=\"title\" width=100>주소</td>\n");
      out.write("		<td colspan=3>{{pur.address}}</td>\n");
      out.write("		<td class=\"title\" w>결재</td>\n");
      out.write("		<td width=100>{{outPayType pur.payType}}</td>\n");
      out.write("		<td class=\"title\" >주문일</td>\n");
      out.write("		<td width=100>\n");
      out.write("\n");
      out.write(" <select id=\"status\">\n");
      out.write("        <option value=\"0\">처리중</option>\n");
      out.write("        <option value=\"1\">처리완료</option>\n");
      out.write("        \n");
      out.write("</select>\n");
      out.write("   <button id=\"btnStatus\" order=\"{{pur.order_id}}\">수정</button>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("<table>\n");
      out.write("	<tr class=\"title\">\n");
      out.write("		<td width=100>이미지</td>	\n");
      out.write("		<td width=100>상품코드</td>	\n");
      out.write(" 		<td width=300>상품명</td>\n");
      out.write("		<td width=100>제조사</td>\n");
      out.write("		<td width=100>가격</td>\n");
      out.write("		<td width=100>수량</td>\n");
      out.write("		<td width=100>금액</td>\n");
      out.write("	</tr>\n");
      out.write("	{{#each array}}\n");
      out.write("	<tr class=\"row\">\n");
      out.write("		<td>\n");
      out.write("			<a href=\"/pro/info?prod_id={{prod_id}}\"><img src=\"/image/shop/{{image}}\" width=50></a>\n");
      out.write("		</td>\n");
      out.write("		<td>{{prod_id}}</td>\n");
      out.write("		<td>{{prod_name}}</td>\n");
      out.write("		<td>{{company}}</td>\n");
      out.write("		<td>{{price}}</td>\n");
      out.write("		<td>{{qnt}}</td>\n");
      out.write("		<td>{{sum}}</td>\n");
      out.write("	</tr>\n");
      out.write("	{{/each}}\n");
      out.write("	<tr class=\"title\">\n");
      out.write("		<td colspan=7>합계: <b>{{total}}</b></td>\n");
      out.write("	</tr>\n");
      out.write("</table>\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	Handlebars.registerHelper(\"outPayType\", function(payType){\n");
      out.write("		if(payType=='0')	return \"무통장\";\n");
      out.write("		else return \"카드\";\n");
      out.write("	})\n");
      out.write("\n");
      out.write("	Handlebars.registerHelper(\"outStatus\", function(status){\n");
      out.write("		if(payType=='0')	return \"무통장\";\n");
      out.write("		else return \"카드\";\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("	\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("	var page=1;\n");
      out.write("	getList();\n");
      out.write("	   \n");
      out.write("	   $(\"#next\").on(\"click\", function(){\n");
      out.write("	      page++;\n");
      out.write("	      getList();\n");
      out.write("	   });\n");
      out.write("	   \n");
      out.write("	   $(\"#prev\").on(\"click\", function(){\n");
      out.write("	      page--;\n");
      out.write("	      getList();\n");
      out.write("	   });\n");
      out.write("	\n");
      out.write("	$(frm).on(\"submit\",function(e){\n");
      out.write("		e.preventDefault();\n");
      out.write("		page=1;\n");
      out.write("		getList();\n");
      out.write("		\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("	$(\"#tbl1\").on(\"click\",\"#btnStatus\",function(){\n");
      out.write("		var order_id=$(this).attr(\"order\");\n");
      out.write("		var status=$(\"#status\").val();\n");
      out.write("		if(!confirm(order_id+\"번 주문의 상태를 \"+ status+ \"로 변경하실래요?\"));\n");
      out.write("		$.ajax({\n");
      out.write("			type:\"get\",\n");
      out.write("			url:\"/update/status\",\n");
      out.write("			data:{id:order_id,status:status},\n");
      out.write("			success:function(){\n");
      out.write("				alert(\"상태가변경되었습니다.\")\n");
      out.write("			}\n");
      out.write("			\n");
      out.write("		})\n");
      out.write("		\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	//구매정보를눌렀을떄 \n");
      out.write("	$(\"#tbl\").on(\"click\",\".row button\",function(){\n");
      out.write("		var id=$(this).attr(\"id\");\n");
      out.write("		$.ajax({\n");
      out.write("			type:\"get\",\n");
      out.write("			url:\"/order/read.json\",\n");
      out.write("			data:{id:id},\n");
      out.write("			dataType:\"json\",\n");
      out.write("			success:function(data){\n");
      out.write("				 var temp=Handlebars.compile($(\"#temp1\").html());\n");
      out.write("		         $(\"#tbl1\").html(temp(data));\n");
      out.write("		         $(\"#status\").val(data.pur.status).prop(\"selected\",ture);\n");
      out.write("			}\n");
      out.write("		})\n");
      out.write("	})\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	$(\"#per,#order,#desc\").on(\"change\",function(){\n");
      out.write("		getList();\n");
      out.write("	})\n");
      out.write("	function getList() {\n");
      out.write("		var key=$(\"#key\").val();\n");
      out.write("		var word=$(\"#word\").val();\n");
      out.write("		var per=$(\"#per\").val();\n");
      out.write("		var order=$(\"#order\").val();\n");
      out.write("		var desc=$(\"#desc\").val();\n");
      out.write("		\n");
      out.write("		$.ajax({\n");
      out.write("			type:\"get\",\n");
      out.write("			url:\"/order/list.json\",\n");
      out.write("			data:{key:key,word:word,per:per,order:order,desc:desc, page:page},\n");
      out.write("			dataType:\"json\",\n");
      out.write("			success:function(data){\n");
      out.write("				 var temp=Handlebars.compile($(\"#temp\").html());\n");
      out.write("		         $(\"#tbl\").html(temp(data));\n");
      out.write("		         $(\"#total\").html(data.total);\n");
      out.write("		            if(data.total==0){\n");
      out.write("		               $(\"#tbl\").append(\"<tr><td colspan=6 class='none'>검색된 주문내역이 없습니다!</td></tr>\");\n");
      out.write("		               $(\".buttons\").hide();\n");
      out.write("		            }else{\n");
      out.write("		               $(\"#page\").html(page + \"/\" + data.last);\n");
      out.write("		               \n");
      out.write("		               if(page==1) $(\"#prev\").attr(\"disabled\", true);\n");
      out.write("		               else $(\"#prev\").attr(\"disabled\", false);\n");
      out.write("		               \n");
      out.write("		               if(page==data.last) $(\"#next\").attr(\"disabled\", true);\n");
      out.write("		               else $(\"#next\").attr(\"disabled\", false);\n");
      out.write("		               $(\".buttons\").show();\n");
      out.write("		            }\n");
      out.write("		         }\n");
      out.write("		      })\n");
      out.write("		   }\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	$.ajax({\n");
      out.write("		type:\"get\",\n");
      out.write("		url:\"/order/list.json\"\n");
      out.write("	})\n");
      out.write("\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
